gushphp/gush

phar-stub.php

The `gush.phar` file, that installer downloads needs to be rebuilt for this change to take effect.
Closes #373

Adds shebang to "gush.phar" file

---

src/Application.php
src/Command/Issue/IssueTakeCommand.php
src/Command/PullRequest/PullRequestMergeCommand.php
src/Helper/GitConfigHelper.php
tests/Command/Issue/IssueTakeCommandTest.php
tests/Command/PullRequest/PullRequestMergeCommandTest.php
tests/Helper/GitConfigHelperTest.php

|Fixed Tickets|None|
Use the (provided) organization for the remote of the `issue:take` command
instead of requiring this to be provided separately.
The `--remote` option is removed to prevent confusion

use organization for issue:take remote

---

src/Command/PullRequest/PullRequestCreateCommand.php
src/Helper/GitHelper.php
tests/Command/PullRequest/PullRequestCreateCommandTest.php

|Fixed Tickets|#407|
Guard the remote branch exists in `pull-request:create`
* check if the remote branch exists
* ask to push when the remote branch doesn't exists but does local
* error when the remote branch doesn't exist and not local or not pushed
TODO:

Guard remote branch exists in pull-request:create

---

src/Command/PullRequest/PullRequestCreateCommand.php
src/Template/PullRequest/Create/DefaultTemplate.php
tests/Command/PullRequest/PullRequestCreateCommandTest.php

While working on big refactoring I found to bugs that should be fixed now.
- The default template for pull-request:create did not ask for a description.
- When no title is provided and no title can be found in the using the first commit an exception was thrown, this should only happen when the command is executed in none-interactive mode.

Bugs pull request create

---

src/Application.php
src/Command/Branch/BranchMergeCommand.php
src/Exception/MergeWorkflowException.php
src/Helper/GitHelper.php
src/Operation/RemoteMergeOperation.php
src/Util/StringUtil.php
src/Validator/MergeWorkflowValidator.php
tests/Command/Branch/BranchMergeCommandTest.php
tests/Helper/GitHelperTest.php
tests/Validator/MergeWorkflowValidatorTest.php

This command does more the just merging, it also guards that the branches are merged according to
a configured workflow (eg no 2.3 to > 2.0).
The workflow is completely adjustable to ones needs, at the moment it supports semver and Git-flow.
And allows to configure constraints to which branches maybe to where.
Todo:

Add BranchMergeCommand for remote merging branches (with a few extra's)

---

src/Command/PullRequest/PullRequestCreateCommand.php
src/Helper/GitHelper.php
tests/Command/PullRequest/PullRequestCreateCommandTest.php

Ensure upstream exists for pull-request:open

---

src/Helper/GitHelper.php

The -u flag does not set the upstream when used with git pull

Remove -u flag when pulling from remote

---

src/ThirdParty/Gitlab/Adapter/GitLabIssueTracker.php

When copying issues between projects, we need to handle most of the details in the source.
I think that it is the first step here, maybe I need to go deeper to analyse issue format for Github / Bitbucket / Gitlab...
Do you think it can be interesting to handle that cases ?

Gitlab: Handle assignee & milestone during issue creation

---

src/ThirdParty/Bitbucket/BitbucketIssueTracker.php

The function used to retrieve the list of issue comments was wrong because it retrieve the issue list instead of the comment list...

Fix the `getComments` method in BitbucketIssueTracker

---

composer.json
src/ThirdParty/Gitlab/Adapter/GitLabIssueTracker.php
src/ThirdParty/Gitlab/Model/Issue.php

The Gitlab API transform all the retrieved data into objects and :
* It was impossible to view issue detail
* It was impossible to view issue comments
This PR normalize the same way than on the others thirdparty libs.

Gitlab: Normalize comments and issues access

---

src/Command/Issue/IssueShowCommand.php
src/ThirdParty/Gitlab/Adapter/GitLabIssueTracker.php

The function used to retrieve the list of issue comments was wrong because it retrieve the issue list instead of the comment list...
Example of output :
```
Issue #2 (invalid): by xxx [xxx]
Type: Issue
Milestone: v0.0.1
Labels: enhancement, major, Bots activity, v0.0.1
Title: [issue title here]
Link: [issue url here]
**Objective:** To know the pace of crawl engines, and have a state of daily crawl.
Comments -------------------------------------------------------------------------------------------
Comment #14179448 by xxx on Tue, 09 Dec 2014 18:27:17 +0000
Link: [comment url here]
[comment body here]
----------
Comment #14153534 by xxx on Mon, 08 Dec 2014 19:46:18 +0000
Link: [comment url here]
[comment body here]
----------
```

Add an option to display issue comments

---

src/Command/Issue/IssueCopyCommand.php
src/ThirdParty/Gitlab/Adapter/GitLabAdapter.php
src/ThirdParty/Gitlab/Adapter/GitLabIssueTracker.php
tests/Command/Issue/IssueCopyCommandTest.php

When using the gitlab adapter to copy an issue from one project to another (in gitlab too) there was some strange behaviours, the issue is copied in the `from` project.
This PR fix the errors here and some others with the Gitlab adapter issue management.

Issue copy problem with the Gitlab adapter

---

src/Helper/TemplateHelper.php
tests/Command/PullRequest/PullRequestCreateCommandTest.php

|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no     |
|New feature? |yes     |
|BC breaks?   |no     |
|Deprecations?|no     |
|Tests pass?  |yes     |
|Fixed tickets|      |
|License      |MIT   |
|Doc PR       |      |
**TODO:**

[pull-request:create] Use `--base` option as default for `branch` template key

---

src/Helper/GitHelper.php

| Bug fix?      | yes
Current regex used to find a branch matches many branches starting with the same
string. By instance, searching for "my", all these branches are a match:
* my
* my-branch
* my-branch2

[pull-request:create] [bugfix] Update regex that checks for existing branches

---

src/Adapter/Adapter.php
src/Adapter/IssueTracker.php
src/Factory/AdapterFactory.php
src/Helper/TemplateHelper.php
src/ThirdParty/Bitbucket/BitbucketAdapter.php
src/ThirdParty/Bitbucket/BitbucketIssueTracker.php
src/ThirdParty/Bitbucket/BitbucketRepoAdapter.php
src/ThirdParty/Github/GitHubAdapter.php
src/ThirdParty/Gitlab/Adapter/GitLabAdapter.php
src/ThirdParty/Gitlab/Adapter/GitLabIssueTracker.php
src/ThirdParty/Gitlab/Adapter/GitLabRepoAdapter.php
src/ThirdParty/Gitlab/Model/MergeRequest.php
tests/Fixtures/Adapter/TestAdapter.php
tests/Fixtures/Adapter/TestIssueTracker.php

Cleaning-up adapter methods and information

---

composer.json

| Bug fix?      | yes
Previously locked revision is already released on `m4tthumphrey/php-gitlab-api: 7.13.1`
https://github.com/m4tthumphrey/php-gitlab-api/commit/5e506195028982ee08a01f31ee43d0db1e9b8d77

[bugfix] Respect semver in requirement for `m4tthumphrey/php-gitlab-api`

---

src/Helper/GitConfigHelper.php
src/Helper/GitHelper.php
src/Helper/ProcessHelper.php
src/Subscriber/CoreInitSubscriber.php
src/Subscriber/GitFolderSubscriber.php
src/Subscriber/GitRepoSubscriber.php
tests/BaseTestCase.php
tests/Command/Branch/BranchChangelogCommandTest.php
tests/Command/PullRequest/PullRequestSemVerCommandTest.php
tests/Command/PullRequest/PullRequestSquashCommandTest.php
tests/Command/Util/MetaHeaderCommandTest.php
tests/Helper/GitHelperTest.php
tests/Subscriber/GitFolderSubscriberTest.php

Remove the caching of process result, this is only used by is `isGitFolder()`. Instead the `GitHelper` keeps the git-folder location itself (within the Helper class).
And add tests for `isGitFolder()`

Remove caching of process result

---

Dockerfile
gush.dist

|Fixed tickets|#595|
[Using SSH agent forwarding](https://developer.github.com/guides/using-ssh-agent-forwarding/).

Use SSH agent forwarding instead of SSH keys

---

circle.yml

`docker-compose` isn't a requirement

---

circle.yml

Ref: https://discuss.circleci.com/t/home-env-var-isnt-resolved-at-dependencies-cache-directories/2825

[bugfix] Fix for Circle CI issue resolving `$HOME` env var

---

src/ThirdParty/Gitlab/Model/Issue.php

This is a little fix about API change in Gitlab. Before milestone details were retrieved as an array, now it's directly the label. I've just added a check on data type to avoid a warning.

Fix invalid milestone name retrieval

---

src/Command/Issue/IssueShowCommand.php
src/Command/PullRequest/PullRequestListCommand.php
src/ThirdParty/Gitlab/Adapter/GitLabIssueTracker.php
src/ThirdParty/Gitlab/Adapter/GitLabRepoAdapter.php

I've found that there are simpler methods to retrieve data from Gitlab API library than the one used for the moment.
Also, Gitlab API response structure is not the same than Github, some keys must be updated.

Apply some normalization on Gitlab API handling

---

composer.json
src/Application.php

Because the release of gush is now based on tagged docker versions, this way of updating the gush image supersedes the phar way. => docker pull coder20078/gush will do

removing kherge unneeded now

---

src/Helper/MetaHelper.php
src/Meta/Base.php
tests/Helper/MetaHelperTest.php

PHP 7 files should have a declare(strict_types=1); but this conflicts with the meta:header command 😅  so this fixes it, and allows any futue declare usage 👍

Fix Meta for PHP files with declare

---

composer.json
src/ThirdParty/Gitlab/Adapter/GitLabRepoAdapter.php

I've just implemented the branch forking feature for Gitlab adapter.
This PR rely on another PR : m4tthumphrey/php-gitlab-api/pull/140 because the forking feature is not possible in the current php-gitlab-api version.
When ready, I'll remove the WIP mention in the title...

Implement `branch:fork` for Gitlab adapter

---

src/Application.php
src/Command/PullRequest/PullRequestShowCommand.php
src/ThirdParty/Gitlab/Adapter/GitLabRepoAdapter.php

This PR is a WIP for the #581 issue. For the moment it can't be merged because the Gitlab API library can't retrieve merge request commits.
I've submitted a PR here: m4tthumphrey/php-gitlab-api#139.
When the PR will be merged and a version released, we can increment dependency number in composer.json and merge that one.
I've also added a new flag `--with-commits` on the `pull-request:show` command.

Add support for pullRequestGetCommits in GitlabRepoAdapter

---

src/Command/PullRequest/PullRequestShowCommand.php
tests/Command/PullRequest/PullRequestShowCommandTest.php

We have for the moment a `issue:show`, I think having a `pull-request:show` is nice too. It's the same logic than for issue :
- It display general details / description
- A flag `--with-comments` allow to display comments

Create a new command to show Pull Request details
