gushphp/gush

composer.json, src/Helper/GitConfigHelper.php
=> ensuring github adapter is sourced as the latest one with various fixes

.bldr.yml, README.md, src/Command/PullRequest/PullRequestMergeCommand.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php
=> switch transport on tests according to @sstok

src/Adapter/Adapter.php, src/Application.php, src/Command/Issue/IssueCopyCommand.php, src/Command/PullRequest/PullRequestSwitchBaseCommand.php, src/Command/Util/MetaConfigureCommand.php, src/Exception/NotImplementedException.php, src/Helper/GitHelper.php, src/Operation/RemoteMergeOperation.php, src/Template/Messages.php
=> cs to review

src/Application.php
=> not requiring configuration file

src/Factory.php, src/Tester/QuestionToken.php
=> finish killing alignments

src/Helper/GitConfigHelper.php, src/Helper/GitHelper.php, tests/Helper/GitConfigHelperTest.php, tests/Helper/GitHelperTest.php
=> add GitConfigHelper::getRemoteInfo()

src/Command/PullRequest/PullRequestSquashCommand.php
=> remove check fixes #213

.travis.yml, box.json, src/Command/Issue/IssueTakeCommand.php, tests/Command/Issue/IssueTakeCommandTest.php
=> consider base integration branch config on i:Take

.gush.yml, .travis.yml, composer.json, src/Command/PullRequest/PullRequestMergeCommand.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php
|Q            |A        |
|---          |---      |
|Fixed Tickets|#389|
|License      |MIT      |
Replaces  #394
=> Add support for requiring a configured pr-type

src/Adapter/SupportsDynamicLabels.php, src/Command/Issue/LabelIssuesCommand.php
=> add support for dynamic labeling

src/Command/Issue/IssueTakeCommand.php, tests/Command/Issue/IssueTakeCommandTest.php
=> Allow `issue:take` to checkout specific org/repo

bin/gush, src/Application.php, src/Command/Core/CoreConfigureCommand.php, src/Command/Core/InitCommand.php, src/Factory/AdapterFactory.php, src/Factory/IssueTrackerFactory.php, src/Factory/LegacyAdapterFactory.php, src/Factory/LegacyIssueTrackerFactory.php, src/Factory/RepositoryManagerFactory.php, src/Helper/StyleHelper.php, src/Tester/Adapter/TestAdapterFactory.php, src/Tester/Adapter/TestConfigurator.php, src/Tester/Adapter/TestIssueTrackerFactory.php, tests/ApplicationTest.php, tests/Command/BaseTestCase.php, tests/Command/Core/CoreConfigureCommandTest.php, tests/Command/Core/CoreInitCommandTest.php, tests/Factory/AdapterFactoryTest.php
|Fixed Tickets|#413|
See commit subjects :)
Some pics:
*First picture is outdated, Jira doesn't support Repository Management, that was a bug :flushed:*
=> Core:configure improvements

src/Operation/RemoteMergeOperation.php
|Fixed Tickets|#371|
This fixes #371 and some minor bugs;
- use the correct remote base when merging (not the local branch)
- fix not being able to squash when `--force-squash` option was provided
- restore original branch after merge operation.
=> fix RemoteMergeOperation to always use an up-to-date remote-base

src/Command/PullRequest/PullRequestCreateCommand.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php
=> Remove pull-reques:create --issue option

src/Application.php
|Fixed Tickets|#428|
This should fix the missing exit-code in the proper way, please rewiew.
=> fix Application missing exit-code in doRunCommand

src/Command/PullRequest/PullRequestMergeCommand.php, src/Helper/GitConfigHelper.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php
=> Ensure notes are fetched pull-request is merged

src/Adapter/Adapter.php, src/Adapter/IssueTracker.php, src/Command/Core/CoreConfigureCommand.php, tests/Fixtures/Adapter/TestAdapter.php, tests/Fixtures/Adapter/TestIssueTracker.php
This removes old (no longer used) methods from the Adapters
=> [2.0] Remove old methods from Adapters

src/Command/PullRequest/PullRequestMergeCommand.php, src/Helper/GitHelper.php, src/Operation/RemoteMergeOperation.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php, tests/Helper/GitHelperTest.php
=> add fast-forward support for pull-request:merge

src/Application.php, src/Command/Branch/BranchChangelogCommand.php, src/Command/Branch/BranchDeleteCommand.php, src/Command/Branch/BranchForkCommand.php, src/Command/Branch/BranchMergeCommand.php, src/Command/Branch/BranchPushCommand.php, src/Command/Branch/BranchRemoteAddCommand.php, src/Command/Branch/BranchSyncCommand.php, src/Command/Core/InitCommand.php, src/Command/Issue/IssueTakeCommand.php, src/Command/PullRequest/PullRequestCreateCommand.php, src/Command/PullRequest/PullRequestFixerCommand.php, src/Command/PullRequest/PullRequestMergeCommand.php, src/Command/PullRequest/PullRequestSemVerCommand.php, src/Command/PullRequest/PullRequestSquashCommand.php, src/Command/PullRequest/PullRequestSwitchBaseCommand.php, src/Command/Util/FabbotIoCommand.php, src/Command/Util/MetaConfigureCommand.php, src/Command/Util/MetaHeaderCommand.php, src/Feature/GitFolderFeature.php, src/Helper/GitHelper.php, src/Subscriber/GitFolderSubscriber.php, tests/Command/Core/CoreInitCommandTest.php, tests/Fixtures/Command/GitFolderCommand.php, tests/Subscriber/GitFolderSubscriberTest.php
=> add GitFolderFeature for Git enabled commands

src/Command/PullRequest/PullRequestCreateCommand.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php
|Q            |A        |
|---          |---      |
|Fixed Tickets|#448 #436|
|License      |MIT      |
=> use org branch-reference for getFirstCommitTitle

src/Command/PullRequest/PullRequestMergeCommand.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php
=> Always ask the PR type in PullRequestMergeCommand

src/Command/PullRequest/PullRequestCreateCommand.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php
=> Automatically push missing pull-request branch

src/Helper/GitConfigHelper.php, tests/Helper/GitConfigHelperTest.php
|Fixed Tickets|#460|
Sorry my regex fu is not very good.
=> Support git urls without a username

.travis.yml, src/Application.php, src/Command/PullRequest/PullRequestCheckoutCommand.php, src/Helper/GitHelper.php, tests/Command/CommandTestCase.php, tests/Command/PullRequest/PullRequestCheckoutCommandTest.php
=> add PullRequestCheckoutCommand

.travis.yml, README.md, composer.json, tests/Subscriber/GitFolderSubscriberTest.php
=> even tests

tests/Subscriber/GitRepoSubscriberTest.php
=> switching to docblock testing and snake case

composer.json, src/Application.php, src/Command/Util/StyleCIPatchCommand.php, src/Helper/DownloadHelper.php, src/Helper/GitHelper.php, src/Operation/RemotePatchOperation.php
|Fixed Tickets|#473|
New pull-request utility command to apply StyleCI patches.
*The FabbotIoCommand can be updated with the same logic.*
=> add StyleCiPatchCommand for StyleCI patches

README.md
=> add badge from styleci

src/Command/Util/StyleCIPatchCommand.php
The command did not work as expected, I only tested this on a none-forked repository so this went unnoticed
=> fix StyleCIPatchCommand

README.md
The dependences badge is wrong and seems pointless to me. The total downloads badge doesn't seem that useful either since it doesn't reflect the actual usage.
=> Removed pointless badges

src/Adapter/Adapter.php, src/Adapter/SupportsDynamicLabels.php, src/Command/PullRequest/PullRequestMilestoneListCommand.php
=> minor adjustments

README.md
Just added some dummy params so github's cache is flushed.
=> Force cache flush

src/Command/Core/InitCommand.php, src/Helper/GushQuestionHelper.php, src/Util/CliValidator.php, tests/BaseTestCase.php, tests/Command/Core/CoreInitCommandTest.php
=> Ensure values are validated for InitCommand

src/Command/PullRequest/PullRequestCreateCommand.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php
=> Upper case first letter of title in PR

src/Application.php
=> Update meta:header to work on less/scss files

src/Command/Repository/RepositoryCreateCommand.php
=> Update help description of RepositoryCreate

src/Command/Util/FabbotIoCommand.php, src/Command/Util/StyleCIPatchCommand.php
|Fixed Tickets|#513|
Updated and tested (https://github.com/twigphp/Twig/pull/1881)
=> Improve patching logic of FabbotIoCommand

src/Command/Branch/BranchPushCommand.php, src/Helper/GitHelper.php, tests/Command/Branch/BranchPushCommandTest.php
=> Add support for `force` with branch:push

src/Command/Issue/IssueCopyCommand.php
For the moment it was only possible to copy issues in the same IssueTracker instance. With this PR, it is now possible to define a specific target adapter.
=> Allow to copy issues to another issue tracker

composer.json
This looks ok to me, superficially, but I've not made details checking. Perhaps care needs to be taken with upgrading the console component in particular.
=> Upgraded symfony

src/Command/Issue/IssueCopyCommand.php
For me copying issue is related to project host migration. I'm currently facing that migration process and I need to maintain all the issue history details.
For that I also migrate comments.
Can you review this and tell me if it's the right way to do that ?
I made another PR about comments (the #542) which seems to be better handled in a specific command.
For the comment copy, I think it can't be detached from the issue copy process because a comment mean nothing outside of it's issue context.
Thanks :smile:
=> Allow to copy comments when copying issue

src/Command/PullRequest/PullRequestMergeCommand.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php
=> Fix PullRequestMerge shows wrong target with switch

.gush.yml, src/Command/PullRequest/PullRequestCreateCommand.php, src/Template/PullRequest/Create/EnterpriseTemplate.php, src/Template/PullRequest/Create/SymfonyTemplate.php, src/Template/PullRequest/Create/ZendFrameworkTemplate.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php, tests/Template/PullRequest/Create/PullRequestCustomTemplateTest.php, tests/Template/PullRequest/Create/SymfonyTemplateTest.php
| Bug fix?      | yes
| Fixed tickets |
| Doc PR        |
Ref: https://github.com/symfony/symfony/blob/master/.github/PULL_REQUEST_TEMPLATE.md
=> Update PR template case based on `PULL_REQUEST_TEMPLATE.md` from Symfony

src/Command/Branch/BranchMergeCommand.php, src/Command/PullRequest/PullRequestMergeCommand.php
| Bug fix?      | yes
| Fixed tickets |
| Doc PR        |
Ref: https://github.com/symfony/symfony/pull/19415
=> [Command] Remove wrong shortcuts at command options

src/Command/PullRequest/PullRequestCreateCommand.php, src/Template/PullRequest/Create/EnterpriseTemplate.php, src/Template/PullRequest/Create/SymfonyTemplate.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php, tests/Template/PullRequest/Create/SymfonyTemplateTest.php
| Fixed tickets |
| Doc PR        |
=> Add "Branch" row at PR templates

src/Command/PullRequest/PullRequestCreateCommand.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php
=> Show which base-branch the pull-request will be opend against

src/Command/PullRequest/PullRequestCreateCommand.php, src/Helper/GitHelper.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php
| BC breaks?    | kinda
| Fixed tickets |
| Doc PR        |
TODO:
=> [pull-request:create] [WIP] Check for commits between local branch and remote base before push

src/Helper/TemplateHelper.php, src/Template/PullRequest/Create/AbstractSymfonyTemplate.php, src/Template/PullRequest/Create/SymfonyTemplate.php, tests/Command/PullRequest/PullRequestCreateCommandTest.php, tests/Template/PullRequest/Create/SymfonyTemplateTest.php
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |yes   |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|      |
|License      |MIT   |
|Doc PR       |      |
**TODO:**
~~- [ ] Improve tests, mainly the logic related to validator.~~
=> [pull-request:create] Allow to define choices in PR table

src/Command/PullRequest/PullRequestMergeCommand.php, src/Helper/GitHelper.php, src/Template/Messages.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php, tests/Fixtures/Adapter/TestAdapter.php, tests/Helper/GitHelperTest.php
| New feature?  | yes
**TODO:**
=> [pull-request:merge] Add a closing comment after closing PR

src/Helper/GitHelper.php
=> [bugfix] Update `GitHelper::getCommitCountBetweenLocalAndBase()` in order to let git count the commits

.gush.yml, src/Command/PullRequest/PullRequestPatOnTheBackCommand.php, src/Template/Pats/PatTemplate.php, src/Template/Pats/Pats.php, tests/Command/PullRequest/PullRequestPatOnTheBackCommandTest.php, tests/Template/Pats/PatTemplateTest.php
| New feature?  | yes
**TODO:**
=> [pull-request:pat] Allow to configure and to choose pats

tests/Helper/GitHelperTest.php
| Fixed tickets | #577
Provide tests to avoid regressions for #577.
=> Add tests for `GitHelper::branchExists()` and `GitHelper::remoteBranchExists()`

.gush.yml, src/Command/PullRequest/PullRequestMergeCommand.php, src/Command/PullRequest/PullRequestPatOnTheBackCommand.php, tests/Command/PullRequest/PullRequestMergeCommandTest.php, tests/Command/PullRequest/PullRequestPatOnTheBackCommandTest.php
=> [pull-request:create] Give a pat to PR's author after merge

.gush.yml, gush, src/ConfigFactory.php
=> Fix Docker env config loading

circle.yml, composer.json
=> Add dev requirement for `phpunit/phpunit`

gush.dist
=> [bugfix] Update `gush.dist`

gush, gush.dist, src/ConfigFactory.php
=> Fix loading of local config in Docker

tests/Command/PullRequest/PullRequestMergeCommandTest.php
=> Fix PullRequestMergeCommandTest failing for some tests

circle.yml, gush.dist
=> Including some changes

circle.yml, tests/Command/Issue/IssueShowCommandTest.php, tests/Helper/GitConfigHelperTest.php, tests/Helper/GitHelperTest.php, tests/Helper/GitRepoHelperTest.php, tests/Helper/MetaHelperTest.php, tests/Subscriber/GitDirectorySubscriberTest.php
=> Improving Tests

Dockerfile, gush
=> Set `WORKDIR` from Dockerfile to `/root/project`

src/Command/Branch/BranchChangelogCommand.php
=> do not blindly hide errors, show them in debug mode (-vvv)

src/Util/StringUtil.php
=> Remove some unnecessary calls and casts at `StringUtil`, add type and return declarations

src/Helper/GitHelper.php
=> Fix cli-arguments for GitHelper::pushToRemote
